name: tests

on:
  push:
    paths-ignore:
    - 'doc/**'
  pull_request:
    paths-ignore:
    - 'doc/**'

jobs:
  unix_tests:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Setup pyinstaller (windows)
      if: startsWith(matrix.os, 'windows')
      run: pip install pyinstaller
    - name: Setup pyinstaller
      if: false == startsWith(matrix.os, 'windows')
      run: pip3 install pyinstaller
    - name: Running Tests (windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        python src\pashmak.py scripts\module-build.pashm
        python src\pashmak.py scripts\update-headers.pashm
        python src\pashmak.py scripts\doc-build.pashm
        python tests\run.py
        python -m PyInstaller src\pashmak.py --onefile
        dist\pashmak.exe -v
    - name: Running Tests
      if: false == startsWith(matrix.os, 'windows')
      run: |
        make all
        make
        ./dist/pashmak -v

    name: ${{ matrix.os }} Python ${{ matrix.python }}
